version: "2"

services:
  selenium:
    image: selenium/standalone-chrome
    command: [/usr/local/bin/selenium.sh]
    volumes:
      - ./scripts:/usr/local/bin
    container_name: selenium

  server:
    image: jeremycraigmartinez/devdot
    command: [npm, run, test-web, --, --ci-test, --skip-initial-build,  --skip-npm-build]
    volumes:
      - ./:/app
    container_name: devdot
    depends_on:
      - "selenium"
