export default {
    ACCESS_TOKEN_EXPIRATION: 'ACCESS_TOKEN_EXPIRATION',
    SUBMIT_DONE: 'SUBMIT_DONE',
    SUBMIT_STARTED: 'SUBMIT_STARTED',
    QUERY_STRING_CHANGED: 'QUERY_STRING_CHANGED',
    PATH_PARAM_CHANGED: 'PATH_PARAM_CHANGED',
    POST_BODY_CHANGED: 'POST_BODY_CHANGED',
    REQUEST_CHANGED: 'REQUEST_CHANGED',
    CONSOLE_ERROR: 'CONSOLE_ERROR',
    ADD_ITEM_TO_POST_BODY_COLLECTION: 'ADD_ITEM_TO_POST_BODY_COLLECTION',
    REMOVE_ITEM_FROM_POST_BODY_COLLECTION: 'REMOVE_ITEM_FROM_POST_BODY_COLLECTION',
    FILL_REQUEST_SAMPLE_DATA: 'FILL_REQUEST_SAMPLE_DATA',
    AUTH_KEY_CHANGED: 'AUTH_KEY_CHANGED',
    RESET_CONSOLE: 'RESET_CONSOLE',
    TOGGLE_AI_CREDS_FOR_CONSOLE_REQUEST: 'TOGGLE_AI_CREDS_FOR_CONSOLE_REQUEST',
    TOGGLE_SHOW_EXCLUDED_POST_BODY_PROPS: 'TOGGLE_SHOW_EXCLUDED_POST_BODY_PROPS',
    USER_PROFILE_FETCHED: 'USER_PROFILE_FETCHED'
};
